steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/soundril/audio-processor",
        "-f",
        "workers/audio-processor/Dockerfile",
        "workers/audio-processor",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/soundril/audio-processor",
      ]
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/soundril/audio-processor"
timeout: "1200s"
options:
  machineType: "E2_HIGHCPU_32"
